<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <title>PHPAkademija Prijava!</title>
    <link rel="stylesheet" type="text/css" href="mystyle.css">
    <!--   <style>   input, textarea { display: block; }
    </style>-->
</head>
<body>
<div class="form-style-6">
<header>
    <ul id="menu">
        <li><a href="/Lesson4/mvc-app/index/index">Naslovnica</a></li>
        <li><a href="/Lesson4/mvc-app/form/index">Prijavi se</a></li>
        <li><a> Login (za admine)</a></li>
    </ul>
</header>

<main>
    <?php echo $content ?>
</main>

<footer>
    <p>&copy; PHP Akademija, 2016</p>
</footer>
</div>
</body>
</html>



