<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <title>PHPAkademija Prijava!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--<link rel="stylesheet" type="text/css" href="mystyle.css"> -->

</head>
<body style="background-color: lightgreen">
<div class="form-style-6">
<header>
    
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="<?=App::config('url')?>index">Naslovnica</a>
    </div>
    <ul class="nav navbar-nav" id="menu">
     <!-- <li class="active"><a href="#">Home</a></li> -->
        <li><a href="<?=App::config('url')?>form">Prijavi se</a></li>
        <li><a href="<?=App::config('url')?>admin"> Login (za admine)</a></li>
    </ul>
  </div>
</nav>

</header>
    <main>
        
        <div class="container">
  <div class="jumbotron">
         <?php echo $content ?>

</div>
     
    </main>


    
      <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; PHP Akademija, 2016</p>
      </div>
    </footer>
    <!--================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    
        <style>  
        /* Sticky footer styles
-------------------------------------------------- */
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: #f5f5f5;
}


/* Custom page CSS
-------------------------------------------------- */
/* Not required for template or sticky footer method. */

body > .container {
  padding: 60px 15px 0;
}
.container .text-muted {
  margin: 20px 0;
}

.footer > .container {
  padding-right: 15px;
  padding-left: 15px;
}

code {
  font-size: 80%;
}

        
        
    </style>
</div>
</body>
</html>